const data = {
	products: [
		{
			name: 'Dress 1',
			slug: 'dress-1',
			category: 'dress',
			image: '/images/shirt1.jpg',
			price: 5000,
			brand: 'Profashion',
			rating: 4.5,
			numReviews: 8,
			countInStock: 12,
			description: 'Our best dress',
		},
		{
			name: 'Dress 2',
			slug: 'dress-2',
			category: 'dress',
			image: '/images/shirt2.jpg',
			price: 3500,
			brand: 'Profashion',
			rating: 4.0,
			numReviews: 3,
			countInStock: 13,
			description: 'Our 2nd best dress',
		},
		{
			name: 'Dress 3',
			slug: 'dress-3',
			category: 'dress',
			image: '/images/shirt3.jpg',
			price: 3750,
			brand: 'Profashion',
			rating: 4.0,
			numReviews: 3,
			countInStock: 13,
			description: 'Our 2nd best dress',
		},
		{
			name: 'Pant 1',
			slug: 'pant-1',
			category: 'Pant',
			image: '/images/pant1.jpg',
			price: 2000,
			brand: 'Profashion',
			rating: 4.0,
			numReviews: 3,
			countInStock: 13,
			description: 'Our totally best Pant',
		},
		{
			name: 'Pant 2',
			slug: 'pant-2',
			category: 'Pant',
			image: '/images/pant2.jpg',
			price: 1500,
			brand: 'Profashion',
			rating: 4.0,
			numReviews: 3,
			countInStock: 13,
			description: 'Our 2nd best Pant',
		},
		{
			name: 'Pant 3',
			slug: 'pant-3',
			category: 'Pant',
			image: '/images/pant3.jpg',
			price: 1000,
			brand: 'Profashion',
			rating: 4.0,
			numReviews: 3,
			countInStock: 13,
			description: 'Our 3rd best Pant',
		},
	],
};

export default data;
